global:
  resolve_timeout: 5m

route:
  receiver: "log"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: "log"
    webhook_configs:
      - url: "http://alert-logger:8081/"
        send_resolved: true
